### PR TITLE
Capacity decoupling

### PR DESCRIPTION
**Pull request by etsauer**
This is a refactoring and enhancement to the capacity management script. It now has several components:

* An API module/library for gathering the data and building a json dictionary of all of the data for:
  * The cluster
  * Individual nodes
  * Namespaces, and pods
* Two "front-ends" for fetching the data
  * A CLI (`cli.py`) that can be run from the command line to print the data, either formatted (like before) or raw json output
  * A web api to serve the json formatted data.

View instructions in capacity-management/README.md for testing.

### CODE REVIEW

**Comment by sabre1041** [comment]
@etsauer hitting the following error on OCP4 and OCP3 environments

```
new namespace quota
{'cluster': {'quota': {'cpu': '', 'memory': ''}}, 'namespaces': {'esauer-sbx': {'quota': {'cpu': 4, 'memory': 17179869184}}}}
existing namespace quota
{'cluster': {'quota': {'cpu': '', 'memory': ''}}, 'namespaces': {'esauer-sbx': {'quota': {'cpu': 2, 'memory': 12884901888}}}}
Traceback (most recent call last):
  File "./cli.py", line 79, in <module>
    do_print(capacity)
  File "./cli.py", line 8, in do_print
    cluster_memory = capacity["cluster"]["totals"]["memory"]
KeyError: 'totals'
```

**Comment by etsauer** [comment]
@sabre1041 fixed.

**Comment by sabre1041** [comment]
@etsauer looks good. One additional change is to add the `application/json` `Content-Type` for the hosted solution. We should be good to merge at that point

**Comment by sabre1041** [comment]
LGTM

**Pull request merged**
