### PR TITLE
use the token variable

### PR DESCRIPTION
**Pull request by duritong**
so you can actually pass it as an argument

### CODE REVIEW

**Comment by etsauer** [comment]
@themoosman can you review this?

**Comment by themoosman** [comment]
This change isn't necessary as lines 29-33 take care of this if a token isn't provided to the script.

```
if [ "$#" -eq 2 ]; then
  token=$2
else
  token=`oc whoami -t`
fi
```

**Comment by etsauer** [comment]
@themoosman from what I'm seeing, the issue isn't that the token isn't captured, but the `token` variable isn't actually passed to the API call, and instead it uses `$(oc whoami -t)` as the value, therefore the `token` variable is never actually used.

**Comment by themoosman** [comment]
Correct. This PR would break the ability to pass a token, i.e. a long lived token, from the command line. @etsauer

**Comment by duritong** [comment]
@themoosman No, this is actually broken *now* and my PR fixes it, so that, what you describe as a behavior (passing a token), actually works. I don't see what my PR breaks.

**Pull request merged**
