### PR TITLE
Updated default-deny and asb networkpolicy.

### PR DESCRIPTION
**Pull request by aelicieguo**
bugzilla for asb networkpolicy: https://bugzilla.redhat.com/show_bug.cgi?id=1469368

There might not be a need for the networkpolicy kube-service-catalog/apiserver.ingress as well if allow-from-same-namespace.yml networkpolicy is applied.

### CODE REVIEW

**Comment by sabre1041** [comment]
@aelicieguo Thanks for the contribution. 

Recent merge brought in an update to the NetworkPolicy API. Would you be able to rebase and resolve the conflicts and we can test and integrate these changes.

**Comment by sabre1041** [comment]
@aelicieguo great. Would you be able to rebase from master as there are still conflicts and then we should be good?

**Comment by aelicieguo** [comment]
@sabre1041 Done. should be good to go.

**Comment by aelicieguo** [comment]
It should be the okay?
[pchoo@localhost openshift-toolkit]$ git status
# On branch master
nothing to commit, working directory clean

**Comment by sabre1041** [comment]
@aelicieguo looks good. merging

**Pull request merged**
