### PR TITLE
gluster-health-check - check for bricks connected

### PR DESCRIPTION
**Pull request by itewk**
#### What does this PR do?
add an additional check to the gluster-health-check script

#### How should this be tested?
run the ./gluster-health-check against an OCP 3 cluster, then turn off a gluster pod and run it again and see the magic

#### Is there a relevant Issue open for this?
no

#### Other Relevant info, PRs, etc.
no

#### Who would you like to review this?
cc: @redhat-cop/casl
cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by itewk** [comment]
@redhat-cop/casl and/or @redhat-cop/day-in-the-life peer review please

**Comment by itewk** [comment]
@garethahealy you reviewed the original MR, may be you can review this one?

**Comment by garethahealy** [comment]
@itewk ; since this one-liner is getting bigger and bigger. is it possible to move it to a script, cp it into the pod and then exec? just thinking about making it more readable

**Comment by itewk** [comment]
possible...sure....worth the efffort....I don't think so. CNS 3 is going to fad out fast enough. I promise if on the edge case I end up updating this again I will do that, but rather just get this in as is since it works.

**Comment by garethahealy** [comment]
nps.

**Pull request merged**
